"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.thirdPartyBaseSchema = exports.baseSchema = exports.stdObjectSchema = exports.stdBaseObjectSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
exports.stdBaseObjectSchema = zod_1.z.object({
    id: zod_1.z.string(),
});
exports.stdObjectSchema = exports.stdBaseObjectSchema;
exports.baseSchema = exports.stdObjectSchema.extend({
    createdAt: zod_1.z.date(),
});
exports.thirdPartyBaseSchema = exports.stdObjectSchema.extend({
    thirdPartyEntityId: zod_1.z.string().optional().nullable(),
    thirdPartyId: zod_1.z.string().optional().nullable(),
});
//# sourceMappingURL=heros.zod.js.map